# apps/teamventure/monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'java-business-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['java-business-service:8080']

  - job_name: 'python-ai-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['python-ai-service:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
